name: CI - Linux via CMake

on:
  push:
    branches:
      - main
      - devel
      - 'topic/**'
  pull_request:
    branches:
      - main
      - devel
  workflow_call:

defaults:
  run:
    shell: bash -leo pipefail {0} {0}
jobs:
  build:
    runs-on: self-hosted
    env:
      CCACHE_DIR: ~/.ccache

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup ccache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}
        path: ${{ env.CCACHE_DIR }}

    - name: Build and install proxnlp
      run: |
        micromamba activate
        cd $GITHUB_WORKSPACE
        mkdir build && cd build

        cmake .. -DBUILD_DOCUMENTATION=OFF \
          -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -DCMAKE_BUILD_TYPE=Release
        make -j6 install
  test:
    needs: build
    runs-on: self-hosted
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
      CTEST_PARALLEL_LEVEL: 4
    steps:
    - run: |
        micromamba activate
        micromamba install pytest casadi -y
        cd $GITHUB_WORKSPACE/build
        make test
