name: CI - Linux via CMake

on:
  push:
    branches:
      - main
      - devel
      - 'topic/**'
  pull_request:
  workflow_dispatch:
  workflow_call:
env:
  CCACHE_DIR: ~/.ccache
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 4
  NJOBS: 8

defaults:
  run:
    shell: bash -leo pipefail {0} {0}
jobs:
  build:
    runs-on: self-hosted
    steps:

    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}
        path: ${{ env.CCACHE_DIR }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Build and install proxnlp
      run: |
        micromamba activate

        cd $GITHUB_WORKSPACE
        mkdir build && cd build

        cmake .. -DBUILD_DOCUMENTATION=OFF \
          -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -DCMAKE_BUILD_TYPE=Release
        make -j$NJOBS install
        python3 -c "import proxnlp"

    - name: Run tests
      run: |
        micromamba activate
        micromamba install pytest casadi -y
        cd $GITHUB_WORKSPACE
        echo "CURRENT DIRECTORY IS $PWD"
        cd build && ctest

  cleanup:
    name: Cleanup
    needs: build
    runs-on: self-hosted
    if: always()
    steps:
    - run: |
        cd $GITHUB_WORKSPACE
        if [ -d build ]; then
          cd build/
          make uninstall || echo "No uninstall target found"
          cd .. && rm -rf build/
        else
          echo "build-dir did not exist"
        fi
